"""initial schema

Revision ID: f2e35d38f616
Revises: 
Create Date: 2026-06-25 10:32:24.974718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e35d38f616'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('sponsor', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('target_wave', sa.String(length=30), nullable=False),
    sa.Column('budget_estimate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contingency_percent', sa.Float(), nullable=False),
    sa.Column('target_start', sa.Date(), nullable=True),
    sa.Column('target_finish', sa.Date(), nullable=True),
    sa.Column('outage_window', sa.String(length=160), nullable=True),
    sa.Column('target_platform', sa.String(length=200), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programmes_package_code'), ['package_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_programmes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_programmes_target_wave'), ['target_wave'], unique=False)
        batch_op.create_index(batch_op.f('ix_programmes_title'), ['title'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=80), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('process_area', sa.String(length=160), nullable=True),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=120), nullable=True),
    sa.Column('support_status', sa.String(length=40), nullable=False),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('business_criticality', sa.Integer(), nullable=False),
    sa.Column('safety_impact', sa.Integer(), nullable=False),
    sa.Column('production_impact', sa.Integer(), nullable=False),
    sa.Column('cyber_exposure', sa.Integer(), nullable=False),
    sa.Column('failure_likelihood', sa.Integer(), nullable=False),
    sa.Column('spares_risk', sa.Integer(), nullable=False),
    sa.Column('recoverability_risk', sa.Integer(), nullable=False),
    sa.Column('dependency_complexity', sa.Integer(), nullable=False),
    sa.Column('evidence_confidence', sa.String(length=1), nullable=False),
    sa.Column('delivery_readiness', sa.Integer(), nullable=False),
    sa.Column('treatment', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('recommended_wave', sa.String(length=30), nullable=False),
    sa.Column('data_completeness', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_programme_id'), ['programme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_recommended_wave'), ['recommended_wave'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_risk_band'), ['risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_support_status'), ['support_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_system_name'), ['system_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_treatment'), ['treatment'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_treatment'))
        batch_op.drop_index(batch_op.f('ix_assets_system_name'))
        batch_op.drop_index(batch_op.f('ix_assets_support_status'))
        batch_op.drop_index(batch_op.f('ix_assets_site'))
        batch_op.drop_index(batch_op.f('ix_assets_risk_score'))
        batch_op.drop_index(batch_op.f('ix_assets_risk_band'))
        batch_op.drop_index(batch_op.f('ix_assets_recommended_wave'))
        batch_op.drop_index(batch_op.f('ix_assets_programme_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_code'))

    op.drop_table('assets')
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programmes_title'))
        batch_op.drop_index(batch_op.f('ix_programmes_target_wave'))
        batch_op.drop_index(batch_op.f('ix_programmes_status'))
        batch_op.drop_index(batch_op.f('ix_programmes_package_code'))

    op.drop_table('programmes')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
